services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "18443:18443"
      - "29000:29000"
    expose:
      - "18444"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./config/bsv/bitcoin.conf:/data/bitcoin.conf
      - node1-data:/data
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node2:18444" ]

  node2:
    container_name: node2
    image: bitcoinsv/bitcoin-sv:1.1.0
#    ports:
#      - "18333:18332"
#      - "28333:28332"
    expose:
      - "18444"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./config/bsv/bitcoin.conf:/data/bitcoin.conf
      - node2-data:/data
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node1:18444" ]

volumes:
  node1-data:
    external: false
  node2-data:
    external: false
