services:
  node1:
    container_name: node1
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "18332:18332"
      - "28332:28332"
    expose:
      - "18332"
      - "18333"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./config/bsv/bitcoin.conf:/data/bitcoin.conf
      - node1-data:/data
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node2:18333", "-connect=node3:18333" ]

  node2:
    container_name: node2
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "18333:18332"
      - "28333:28332"
    expose:
      - "18332"
      - "18333"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./config/bsv/bitcoin.conf:/data/bitcoin.conf
      - node2-data:/data
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node1:18333", "-connect=node3:18333" ]

  node3:
    container_name: node3
    image: bitcoinsv/bitcoin-sv:1.1.0
    ports:
      - "18334:18332"
      - "28334:28332"
    expose:
      - "18332"
      - "18333"
    healthcheck:
      test: [ "CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo" ]
    volumes:
      - ./config/bsv/bitcoin.conf:/data/bitcoin.conf
      - node3-data:/data
    command: [ "/entrypoint.sh", "bitcoind", "-connect=node1:18333", "-connect=node2:18333" ]


volumes:
  node1-data:
    external: false
  node2-data:
    external: false
  node3-data:
    external: false
